version: "3.7"

services:
  jupyterlab:
    image: kudoshunsuke/docker-jupyterlab
    build:
      context: ./
      dockerfile: ./jupyterlab/Dockerfile
    ports:
      - "18888:8888"
    tty: true
    #command: bash
    volumes:
      - ./jupyterlab/ws:/home/jupyter/ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/video0:/dev/video0:mwr
      - /dev/video1:/dev/video1:mwr
    logging:
      driver: "json-file" # defaults if not specified
      options:
        max-size: "1m"
        max-file: "1"
